name: flutter_datawedge
description: A Flutter package to communicate with Zebra DataWedge scanners using the DataWedge Intent API
version: 2.1.0
homepage: https://github.com/circus-kitchens/flutter_datawedge
repository: https://github.com/circus-kitchens/flutter_datawedge

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.13.1'

dependencies:
  async: ^2.11.0
  collection: ^1.17.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  stream_transform: ^2.1.0
  json_annotation: ^4.8.1
  strict_json: ^2.2.1
  freezed_result: ^1.0.3+1
  uuid: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  lints: ^2.1.1


flutter:
  plugin:
    platforms:
      android:
        package: com.circuskitchens.flutter_datawedge
        pluginClass: FlutterDatawedgePlugin
