name: flutter_datawedge
description: A Flutter package to communicate with Zebra DataWedge scanners using the DataWedge Intent API
version: 2.0.0-dev.1
homepage: https://github.com/circus-kitchens/flutter_datawedge
repository: https://github.com/circus-kitchens/flutter_datawedge

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  async: ^2.9.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  stream_transform: ^2.1.0
  json_annotation: ^4.8.0
  strict_json: ^2.0.6
  freezed_result: ^1.0.3+1
  mason_logger: ^0.2.8

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  pigeon: ^10.1.0
  json_serializable: ^6.6.1
  lints: ^2.0.1
  very_good_analysis: ^5.0.0+1

flutter:
  plugin:
    platforms:
      android:
        package: com.circuskitchens.flutter_datawedge
        pluginClass: FlutterDatawedgePlugin
